### PR TITLE
Use R CMD Check action

### LINKED ISSUE #64: add a `R CMD check` GH Action that runs on PRs and push to `main`
probably based on https://github.com/r-lib/actions/blob/v2-branch/examples/check-standard.yaml

### PR DESCRIPTION
**Pull request by jdhoffa**
- Use r cmd check action
- Update README

Closes #64

### CODE REVIEW

**Review by jacobvjk — APPROVED** [review]
LGTM based on the example CJ posted, but I will have to trust this is the right setup

**Comment by jdhoffa** [comment]
I just use `usethis::use_github_actions()` and the rest comes free

**Comment by jdhoffa** [comment]
Note: Actions fail, but that's the point! Merging now.

**Comment by jacobvjk** [comment]
> Note: Actions fail, but that's the point! Merging now.

correct and this should fix it #49

**Pull request merged**
