### PR TITLE
Update _pkgdown.yml

### LINKED ISSUE #93: vignettes do not show

### PR DESCRIPTION
**Pull request by jacobvjk**
assuming this may close #93 

fyi @jdhoffa

### CODE REVIEW

**Review by jdhoffa — APPROVED** [review]
lgtm!

**Review by jdhoffa — CHANGES_REQUESTED** [review]
As @cjyetman has pointed out, you will actually also need to update your `DESCRIPTION` file to point to the correct repo. 

See https://github.com/RMI-PACTA/pacta.data.scraping/pull/33/files

**Comment by jdhoffa** [comment]
Looks great. 
This LGTM but I would say depends on https://github.com/RMI-PACTA/pacta.pkgdown.rmitemplate/pulls (which should make the `pkgdown` action pass)

**Comment by jacobvjk** [comment]
I'll wait merging this then

**Pull request merged**
